### ISSUE TITLE
Problem in compiling the banking system

### ISSUE THREAD

**Issue by jason088** [david-daly/CT414-Distributed-Systems-Banking-Application#4]
How to run this banking system as to how to compile the various java files (the order of compiling);
When I compile the files it shows a lot of errors so please guide me how to run this system.

**Comment by david-daly** [comment]
Hi Jason.

Thanks for checking out the project! Sorry that the instructions on how to compile this properly are not provided, that is definitely something I need to add.

For now though the following steps should work:

1) Compile the interfaces into a JAR file
- In the src directory type `javac -cp <root_from_C:_to_\src interfaces\*.java`
  This will compile the interfaces into .class files
- Then type `jar cvf bank.jar interfaces\*.class` 
   Again from the `src` directory. This will compile a class out of the interface files. 

2) Compile the client files
- in the `src` directory again type `javac client\ATM.java`

3) Now all the files are compiled. The next step is to start the rmiregistry:
- type `rmiregistry 7777` (can be any port, this will start the registry on port 7777)

4) In a new console tab start the server:
- type `java server.Bank 7777` (needs to be the same port as the rmiregistry.

5) In a new console tab start the client and use client actions:
- type `java client.ATM localhost 7777 login user1 pass1` (this will open the client and create a session in the server.

6) The other methods can then be used (note: You will need to type the sessionID returned from login into all other requests:

###Deposit: `java client.ATM localhost 7777 deposit 88769912 200 <sessionId>` (This will lodge 200 to account 88769912, <sessionId> is the sesssionId returned by login)

###Withdraw: `java client.ATM localhost 7777 withdraw 88769912 <sessionId>` (This will withdraw 50 to account 88769912, <sessionId> is the sesssionId returned by login)

###Balance: `java client.ATM localhost 7777 inquiry 88769912 <sessionId>` (This will show the balance for account 88769912, <sessionId> is the sesssionId returned by login)

###Statement: `java client.ATM localhost 7777 statement 88769912 <date1> <date2> <sessionId>` (This will show transactions for account 88769912 between 2 dates (must be American format), <sessionId> is the sesssionId returned by login)

Hope this helps. If you have other questions I will do my best to answer them here.

**Comment by jason088** [comment]
Thanks for the very helpful reply...just one issue popped up while i was following the above steps..
after I start the server in a new console by typing in "java server.Bank 7777",this error comes up:
C:\Users\user\banking\src>java server.Bank 7777

--------------------
Security Manager Set
java.security.AccessControlException: access denied ("java.net.SocketPermission" "127.0.0.1:7777" "connect,resolve")
        at java.security.AccessControlContext.checkPermission(Unknown Source)
        at java.security.AccessController.checkPermission(Unknown Source)
        at java.lang.SecurityManager.checkPermission(Unknown Source)
        at java.lang.SecurityManager.checkConnect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at java.net.Socket.<init>(Unknown Source)
        at java.net.Socket.<init>(Unknown Source)
        at sun.rmi.transport.proxy.RMIDirectSocketFactory.createSocket(Unknown Source)
        at sun.rmi.transport.proxy.RMIMasterSocketFactory.createSocket(Unknown Source)
        at sun.rmi.transport.tcp.TCPEndpoint.newSocket(Unknown Source)
        at sun.rmi.transport.tcp.TCPChannel.createConnection(Unknown Source)
        at sun.rmi.transport.tcp.TCPChannel.newConnection(Unknown Source)
        at sun.rmi.server.UnicastRef.newCall(Unknown Source)
        at sun.rmi.registry.RegistryImpl_Stub.rebind(Unknown Source)
        at server.Bank.main(Bank.java:44)


Please suggest a solution to this problem.

**Comment by jason088** [comment]
Thanks for the very helpful reply...just one issue popped up while i was following the above steps..
after I start the server in a new console by typing in "java server.Bank 7777",this error comes up:
C:\Users\user\banking\src>java server.Bank 7777

--------------------
Security Manager Set
java.security.AccessControlException: access denied ("java.net.SocketPermission" "127.0.0.1:7777" "connect,resolve")
        at java.security.AccessControlContext.checkPermission(Unknown Source)
        at java.security.AccessController.checkPermission(Unknown Source)
        at java.lang.SecurityManager.checkPermission(Unknown Source)
        at java.lang.SecurityManager.checkConnect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at java.net.Socket.<init>(Unknown Source)
        at java.net.Socket.<init>(Unknown Source)
        at sun.rmi.transport.proxy.RMIDirectSocketFactory.createSocket(Unknown Source)
        at sun.rmi.transport.proxy.RMIMasterSocketFactory.createSocket(Unknown Source)
        at sun.rmi.transport.tcp.TCPEndpoint.newSocket(Unknown Source)
        at sun.rmi.transport.tcp.TCPChannel.createConnection(Unknown Source)
        at sun.rmi.transport.tcp.TCPChannel.newConnection(Unknown Source)
        at sun.rmi.server.UnicastRef.newCall(Unknown Source)
        at sun.rmi.registry.RegistryImpl_Stub.rebind(Unknown Source)
        at server.Bank.main(Bank.java:44)


Please suggest a solution to this problem.

**Comment by david-daly** [comment]
Hi Jason. Ok, thanks. I think I might know the cause of your issue, I think its the security policy for the rmi server.

There is a piece of code that you will need to change to fix this, as I hardcoded the route to the security policy in `Bank.java` to save me having to type it in all the time when I wanted to run the application.

To fix this, you will need to open up the `Bank.java` file and go to `line 36`. On this line change the path to `all.policy` to be the directory of the project on your computer to `all.policy`.

After that you will need to go through the compilation steps listed above again, and also compile the server classes by typing `javac server/*.java` from the `src` directory.

Sorry for the confusion there, that file really shouldn't be hardcoded, but I am fairly confident that this will fix your issue.

**Comment by david-daly** [comment]
I have also updated the code in master to fix that problem by removing the hardcoded file path. Now to run the server you have to pass in the security manager path as an argument:

`java -Djava.security.policy=all.policy server.Bank 7777` from the `src` directory.

You can pull these changes, recompile everything and run the server with that argument, and it will work or you can follow my comment above and the server will run without pulling the latest changes.

Hope it works for you now!

**Comment by jason088** [comment]
Hi David !!.. Thanks a lot now the system is working perfectly fine on my PC ,I had to do the changes in the policy file also ..Thank you again ,Cheers :)

**Comment by david-daly** [comment]
Cool, glad that its working now and glad that I could help!
